### ISSUE TITLE
SoundChecker - Test THD and SNR - The graph at the bottom does not show completely?

### ISSUE THREAD

**Issue by xiaotongtzhao** [google/sound-checker#16]
1. Launch Sound-Checker
2. Select "Test THD and SNR"
3. Select input device / output device
4. Start the test

EXPECTED
We can see the whole wave graph (from top to the bottom)

ACTUAL
The bottom part of waves got cut

Tested on Pixel 7 and Pixel 7 Pro. Same results.

**Comment by philburk** [comment]
The wave display may be going to zero, which can look cut off.

The "logarithmic" checkbox should be below the graph in the latest version of SoundChecker.
Please update to the newest version.

**Comment by philburk** [comment]
This is as intended. You are seeing the bottom of the graph.
