### ISSUE TITLE
SoundChecker - Test THD and SNR - The graph at the bottom shows off the area 

### ISSUE THREAD

**Issue by xiaotongtzhao** [google/sound-checker#17]
Launch SoundChecker
Select "Test THD and SNR"
Select Input device as Auto select; output device as Auto select
Start the test
Turn volume up and down

EXPECTED
The graph is shown off the area, into the check box area

ACTUAL
The graph shows inside the graph area

See attached screen for details
![Screenshot_20231213-111649](https://github.com/google/sound-checker/assets/143036614/a0830c93-923e-4624-87cb-569b287d8dd7)

**Comment by robertwu1** [comment]
Increased to -250dB from -160dB.
