### ISSUE TITLE
Cannot build using Gradle 8.0.0

### ISSUE THREAD

**Issue by philburk** [google/sound-checker#4]
I checked out Sound-Checker using:

    git clone https://github.com/google/sound-checker.git

I then opened the top Android Studio project on my Macbook and got this error:

The project is using an incompatible version (AGP 8.0.0) of the Android Gradle plugin. Latest supported version is AGP 7.2.2
See Android Studio & AGP compatibility options.

**Comment by philburk** [comment]
We had similar gradle version problems on Oboe:
https://github.com/google/oboe/issues/1815

**Comment by philburk** [comment]
Here is a chart of gradle and java versions that are compatible.
https://docs.gradle.org/current/userguide/compatibility.html

My local Oboe build is using Java 17.
The default Java for Flamingo is Java 11.

**Comment by flamme** [comment]
I could not build on mac either. And then I update my Android studio. Then it worked! Phil, what is your Android studio version? I can confirm it works with the latest one(Android studio Giraffe) on mac.

**Comment by philburk** [comment]
I installed the 2022 Giraffe version of Android Studio and now it works.
